# Generated by Django 3.2.16 on 2023-01-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_value',
            new_name='total_qtd',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.product'),
        ),
    ]
